#region Copyright
//
// Authors:
//   Stefan Lange (mailto:Stefan.Lange@PdfPinata.com)
//   Klaus Potzesny (mailto:Klaus.Potzesny@PdfPinata.com)
//   David Stephensen (mailto:David.Stephensen@PdfPinata.com)
//
// Copyright (c) 2001-2009 empira Software GmbH, Cologne (Germany)
//
// http://www.PdfPinata.com
// http://www.migradoc.com
// http://sourceforge.net/projects/pdfsharp
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#endregion

namespace PinataLayout.DocumentObjectModel;

/// <summary>
/// Represents ids for error and diagnostic messages generated by the PinataLayout DOM.
/// </summary>
internal enum DomMsgID
{

  // ----- General Messages ---------------------------------------------------------------------
  StyleExpected,
  BaseStyleRequired,
  EmptyBaseStyle,
  InvalidFieldFormat,
  InvalidInfoFieldName,
  UndefinedBaseStyle,
  InvalidUnitValue,
  InvalidUnitType,
  InvalidEnumForLeftPosition,
  InvalidEnumForTopPosition,
  InvalidColorString,
  InvalidFontSize,
  InsertNullNotAllowed,
  ParentAlreadySet,
  MissingObligatoryProperty,
  InvalidDocumentObjectType,

  // ----- DdlReader Messages -------------------------------------------------------------------

  Success = 1000,

  SymbolExpected,
  SymbolsExpected,
  OperatorExpected,
  KeyWordExpected,
  EndOfFileExpected,
  UnexpectedEndOfFile,

  StyleNameExpected,

  UnexpectedSymbol,

  IdentifierExpected,
  BoolExpected,
  RealExpected,
  IntegerExpected,
  StringExpected,
  NullExpected,
  NumberExpected,

  InvalidEnum,
  InvalidType,
  InvalidAssignment,
  InvalidValueName,
  InvalidRange,
  InvalidColor,
  InvalidFieldType,
  InvalidValueForOperation,
  InvalidSymbolType,

  MissingBraceLeft,
  MissingBraceRight,
  MissingBracketLeft,
  MissingBracketRight,
  MissingParenLeft,
  MissingParenRight,
  MissingComma,

  SymbolNotAllowed,
  SymbolIsNotAnObject,

  UnknownChartType,

  NoAccess,

  NewlineInString,
  EscapeSequenceNotAllowed,
  NullAssignmentNotSupported,
  OutOfRange,

  UseOfUndefinedBaseStyle,
  UseOfUndefinedStyle,
  NestedFootnote
}
